# Tomcat
server:
  port: 9903

# Spring
spring:
  application:
    name: transaction-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  config:
    import:
      - nacos:transaction-service-dev.yml

wechat:
  app-id: ${WECHAT_APP_ID:wxec253319064722ad}
  mch-id: ${WECHAT_MCH_ID:1600000001}
