DROP TABLE IF EXISTS requests;
CREATE TABLE requests (
  request_id BIGINT NOT NULL AUTO_INCREMENT,
  sender_id BIGINT NOT NULL COMMENT '发起人ID',
  sender_type CHAR(1) NOT NULL COMMENT '发起人类型 0会员 1教练',
  type VARCHAR(50) NOT NULL COMMENT '请求类型，见RequestConstants',
  ref_id BIGINT DEFAULT NULL COMMENT '关联资源ID（教案ID/训练方法ID/课程安排ID等）',
  target_store_id BIGINT DEFAULT NULL COMMENT '目标店铺ID（换店场景）',
  status CHAR(1) DEFAULT '0' COMMENT '整体状态 0待处理 1全部同意 2已拒绝',
  message VARCHAR(500) DEFAULT NULL COMMENT '申请说明',
  reject_reason VARCHAR(255) DEFAULT NULL COMMENT '拒绝原因',
  approver1_id BIGINT DEFAULT NULL COMMENT '审核人1 ID',
  approver1_status CHAR(1) DEFAULT '0' COMMENT '审核人1状态 0待审 1同意 2拒绝',
  approver2_id BIGINT DEFAULT NULL COMMENT '审核人2 ID',
  approver2_status CHAR(1) DEFAULT NULL COMMENT '审核人2状态',
  approver3_id BIGINT DEFAULT NULL COMMENT '审核人3 ID（系统管理员）',
  approver3_status CHAR(1) DEFAULT NULL COMMENT '审核人3状态',
  create_time DATETIME DEFAULT NULL,
  update_time DATETIME DEFAULT NULL,
  PRIMARY KEY (request_id),
  KEY idx_req_sender_id (sender_id),
  KEY idx_req_approver1 (approver1_id),
  KEY idx_req_approver2 (approver2_id),
  KEY idx_req_approver3 (approver3_id),
  KEY idx_req_type_status (type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
