# Tomcat
server:
  port: 8080

# Spring
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        max-content-length: 52428800
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD_ADDR:127.0.0.1:8718}
      datasource:
        ds1:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            dataId: sentinel-gateway
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
  webflux:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import:
      - nacos:gateway-dev.yml
