# Tomcat
server:
  port: 9902

# Spring
spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  mail:
    host: smtp.qq.com
    port: 465
    username: 2244509212@qq.com
    password: olrxpjizyquweadh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  config:
    import:
      - nacos:user-service-dev.yml

wechat:
  app-id: wx1234567890abcdef
  app-secret: abcdef123
