# Tomcat
server:
  port: 9902

# Spring
spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  config:
    import:
      - nacos:user-service-dev.yml

# 文件服务图片访问基础地址
file:
  pic-base-url: http://127.0.0.1:9900/pics

weChat:
  app-id: wx1234567890abcdef
  app-secret: abcdef123
