# Tomcat
server:
  port: 9901

# Spring
spring:
  application:
    name: admin-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  mail:
    host: smtp.qq.com
    port: 465
    username: 2244509212@qq.com
    password: olrxpjizyquweadh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  config:
    import:
      - nacos:admin-service-dev.yml

# 文件服务图片访问基础地址
file:
  pic-base-url: http://127.0.0.1:9900/pics
